// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#pragma once

#include "djinni_support.hpp"
#include "updated_values.hpp"

namespace djinni_generated {

class NativeUpdatedValues final {
public:
    using CppType = ::dependency_evaluator::UpdatedValues;
    using JniType = jobject;

    using Boxed = NativeUpdatedValues;

    ~NativeUpdatedValues();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeUpdatedValues();
    friend ::djinni::JniClass<NativeUpdatedValues>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/example/sankar_5526/helloworld/UpdatedValues") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(IILjava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mRow { ::djinni::jniGetFieldID(clazz.get(), "mRow", "I") };
    const jfieldID field_mColumn { ::djinni::jniGetFieldID(clazz.get(), "mColumn", "I") };
    const jfieldID field_mActualValue { ::djinni::jniGetFieldID(clazz.get(), "mActualValue", "Ljava/lang/String;") };
    const jfieldID field_mFormulaValue { ::djinni::jniGetFieldID(clazz.get(), "mFormulaValue", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
