// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#include "NativeUpdatedValues.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeUpdatedValues::NativeUpdatedValues() = default;

NativeUpdatedValues::~NativeUpdatedValues() = default;

auto NativeUpdatedValues::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeUpdatedValues>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.row)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.column)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.actualValue)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.formulaValue)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeUpdatedValues::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeUpdatedValues>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mRow)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mColumn)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mActualValue)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mFormulaValue))};
}

}  // namespace djinni_generated
