// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#pragma once

#include "cell.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCell final {
public:
    using CppType = ::dependency_evaluator::Cell;
    using JniType = jobject;

    using Boxed = NativeCell;

    ~NativeCell();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeCell();
    friend ::djinni::JniClass<NativeCell>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/example/sankar_5526/helloworld/Cell") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;)V") };
    const jfieldID field_mFormulaValue { ::djinni::jniGetFieldID(clazz.get(), "mFormulaValue", "Ljava/lang/String;") };
    const jfieldID field_mActualValue { ::djinni::jniGetFieldID(clazz.get(), "mActualValue", "Ljava/lang/String;") };
    const jfieldID field_mDependents { ::djinni::jniGetFieldID(clazz.get(), "mDependents", "Ljava/util/ArrayList;") };
    const jfieldID field_mPrecedents { ::djinni::jniGetFieldID(clazz.get(), "mPrecedents", "Ljava/util/ArrayList;") };
    const jfieldID field_mExpressionTokens { ::djinni::jniGetFieldID(clazz.get(), "mExpressionTokens", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
