// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#include "NativeMyRecord.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeMyRecord::NativeMyRecord() = default;

NativeMyRecord::~NativeMyRecord() = default;

auto NativeMyRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeMyRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.key1)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.key2)),
                                                           ::djinni::get(::djinni::List<::djinni::List<::djinni::String>>::fromCpp(jniEnv, c.key3)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeMyRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeMyRecord>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mKey1)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mKey2)),
            ::djinni::List<::djinni::List<::djinni::String>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mKey3))};
}

}  // namespace djinni_generated
