// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#pragma once

#include <string>
#include <utility>
#include <vector>

namespace dependency_evaluator {

struct Cell final {
    std::string formulaValue;
    std::string actualValue;
    std::vector<std::string> dependents;
    std::vector<std::string> precedents;
    std::vector<std::string> expressionTokens;


    Cell() {

    }


    Cell(std::string formulaValue_,
         std::string actualValue_,
         std::vector<std::string> dependents_,
         std::vector<std::string> precedents_,
         std::vector<std::string> expressionTokens_)
    : formulaValue(std::move(formulaValue_))
    , actualValue(std::move(actualValue_))
    , dependents(std::move(dependents_))
    , precedents(std::move(precedents_))
    , expressionTokens(std::move(expressionTokens_))
    {}
};

}  // namespace dependency_evaluator
