// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#pragma once

#include <string>

namespace dependency_evaluator {

class MyClientInterface {
public:
    virtual ~MyClientInterface() {}

    virtual void log_string(const std::string & str) = 0;
};

}  // namespace dependency_evaluator
