// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace dependency_evaluator {

struct MyRecord final {
    int32_t key1;
    std::string key2;
    std::vector<std::vector<std::string>> key3;

    MyRecord() {

    }
    MyRecord(int32_t key1_,
             std::string key2_,
             std::vector<std::vector<std::string>> key3_)
    : key1(std::move(key1_))
    , key2(std::move(key2_))
    , key3(std::move(key3_))
    {}
};

}  // namespace dependency_evaluator
