// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace dependency_evaluator {

struct UpdatedValues final {
    int32_t row;
    int32_t column;
    std::string actualValue;
    std::string formulaValue;

    UpdatedValues(int32_t row_,
                  int32_t column_,
                  std::string actualValue_,
                  std::string formulaValue_)
    : row(std::move(row_))
    , column(std::move(column_))
    , actualValue(std::move(actualValue_))
    , formulaValue(std::move(formulaValue_))
    {}
};

}  // namespace dependency_evaluator
