// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import <Foundation/Foundation.h>

@interface HWCell : NSObject
- (nonnull instancetype)initWithFormulaValue:(nonnull NSString *)formulaValue
                                 actualValue:(nonnull NSString *)actualValue
                                  dependents:(nonnull NSArray<NSString *> *)dependents
                                  precedents:(nonnull NSArray<NSString *> *)precedents
                            expressionTokens:(nonnull NSArray<NSString *> *)expressionTokens;
+ (nonnull instancetype)cellWithFormulaValue:(nonnull NSString *)formulaValue
                                 actualValue:(nonnull NSString *)actualValue
                                  dependents:(nonnull NSArray<NSString *> *)dependents
                                  precedents:(nonnull NSArray<NSString *> *)precedents
                            expressionTokens:(nonnull NSArray<NSString *> *)expressionTokens;

@property (nonatomic, readonly, nonnull) NSString * formulaValue;

@property (nonatomic, readonly, nonnull) NSString * actualValue;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * dependents;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * precedents;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * expressionTokens;

@end
