// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import "HWCell.h"


@implementation HWCell

- (nonnull instancetype)initWithFormulaValue:(nonnull NSString *)formulaValue
                                 actualValue:(nonnull NSString *)actualValue
                                  dependents:(nonnull NSArray<NSString *> *)dependents
                                  precedents:(nonnull NSArray<NSString *> *)precedents
                            expressionTokens:(nonnull NSArray<NSString *> *)expressionTokens
{
    if (self = [super init]) {
        _formulaValue = [formulaValue copy];
        _actualValue = [actualValue copy];
        _dependents = [dependents copy];
        _precedents = [precedents copy];
        _expressionTokens = [expressionTokens copy];
    }
    return self;
}

+ (nonnull instancetype)cellWithFormulaValue:(nonnull NSString *)formulaValue
                                 actualValue:(nonnull NSString *)actualValue
                                  dependents:(nonnull NSArray<NSString *> *)dependents
                                  precedents:(nonnull NSArray<NSString *> *)precedents
                            expressionTokens:(nonnull NSArray<NSString *> *)expressionTokens
{
    return [[self alloc] initWithFormulaValue:formulaValue
                                  actualValue:actualValue
                                   dependents:dependents
                                   precedents:precedents
                             expressionTokens:expressionTokens];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p formulaValue:%@ actualValue:%@ dependents:%@ precedents:%@ expressionTokens:%@>", self.class, (void *)self, self.formulaValue, self.actualValue, self.dependents, self.precedents, self.expressionTokens];
}

@end
