// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import "HWUpdatedValues.h"
#import <Foundation/Foundation.h>
@class HWDependencyEvaluator;


@interface HWDependencyEvaluator : NSObject

+ (nullable HWDependencyEvaluator *)create;

- (nonnull NSArray<NSString *> *)getParsedString:(nonnull NSString *)expression;

- (void)evaluateExpression:(nonnull NSString *)actualExpression
                expression:(nonnull NSArray<NSString *> *)expression
                       row:(int32_t)row
                    column:(int32_t)column
               currentCell:(nonnull NSString *)currentCell;

- (void)storeCellValueConstant:(nonnull NSString *)constant
                           row:(int32_t)row
                        column:(int32_t)column;

- (void)storeCellValueFormula:(nonnull NSString *)expression;

- (nonnull NSArray<HWUpdatedValues *> *)returnUpdatedValues:(nonnull NSString *)expression
                                                        row:(int32_t)row
                                                     column:(int32_t)column
                                                     source:(nonnull NSString *)source
                                               fromActivity:(int32_t)fromActivity;

- (void)createHugeMemory;

@end
