// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#include "dependency_evaluator.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWDependencyEvaluator;

namespace djinni_generated {

class DependencyEvaluator
{
public:
    using CppType = std::shared_ptr<::dependency_evaluator::DependencyEvaluator>;
    using CppOptType = std::shared_ptr<::dependency_evaluator::DependencyEvaluator>;
    using ObjcType = HWDependencyEvaluator*;

    using Boxed = DependencyEvaluator;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

