// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import <Foundation/Foundation.h>


@protocol HWMyClientInterface

- (void)logString:(nonnull NSString *)str;

@end
