// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import "HWMyRecord.h"
#include "my_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWMyRecord;

namespace djinni_generated {

struct MyRecord
{
    using CppType = ::dependency_evaluator::MyRecord;
    using ObjcType = HWMyRecord*;

    using Boxed = MyRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
