// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import <Foundation/Foundation.h>

@interface HWMyRecord : NSObject
- (nonnull instancetype)initWithKey1:(int32_t)key1
                                key2:(nonnull NSString *)key2
                                key3:(nonnull NSArray<NSArray<NSString *> *> *)key3;
+ (nonnull instancetype)myRecordWithKey1:(int32_t)key1
                                    key2:(nonnull NSString *)key2
                                    key3:(nonnull NSArray<NSArray<NSString *> *> *)key3;

@property (nonatomic, readonly) int32_t key1;

@property (nonatomic, readonly, nonnull) NSString * key2;

@property (nonatomic, readonly, nonnull) NSArray<NSArray<NSString *> *> * key3;

@end
