// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import "HWMyRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto MyRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.key1),
            ::djinni::String::toCpp(obj.key2),
            ::djinni::List<::djinni::List<::djinni::String>>::toCpp(obj.key3)};
}

auto MyRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[HWMyRecord alloc] initWithKey1:(::djinni::I32::fromCpp(cpp.key1))
                                       key2:(::djinni::String::fromCpp(cpp.key2))
                                       key3:(::djinni::List<::djinni::List<::djinni::String>>::fromCpp(cpp.key3))];
}

}  // namespace djinni_generated
