// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import "HWUpdatedValues.h"
#include "updated_values.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWUpdatedValues;

namespace djinni_generated {

struct UpdatedValues
{
    using CppType = ::dependency_evaluator::UpdatedValues;
    using ObjcType = HWUpdatedValues*;

    using Boxed = UpdatedValues;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
