// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import "HWUpdatedValues+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto UpdatedValues::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.row),
            ::djinni::I32::toCpp(obj.column),
            ::djinni::String::toCpp(obj.actualValue),
            ::djinni::String::toCpp(obj.formulaValue)};
}

auto UpdatedValues::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[HWUpdatedValues alloc] initWithRow:(::djinni::I32::fromCpp(cpp.row))
                                         column:(::djinni::I32::fromCpp(cpp.column))
                                    actualValue:(::djinni::String::fromCpp(cpp.actualValue))
                                   formulaValue:(::djinni::String::fromCpp(cpp.formulaValue))];
}

}  // namespace djinni_generated
