// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

#import "HWUpdatedValues.h"


@implementation HWUpdatedValues

- (nonnull instancetype)initWithRow:(int32_t)row
                             column:(int32_t)column
                        actualValue:(nonnull NSString *)actualValue
                       formulaValue:(nonnull NSString *)formulaValue
{
    if (self = [super init]) {
        _row = row;
        _column = column;
        _actualValue = [actualValue copy];
        _formulaValue = [formulaValue copy];
    }
    return self;
}

+ (nonnull instancetype)updatedValuesWithRow:(int32_t)row
                                      column:(int32_t)column
                                 actualValue:(nonnull NSString *)actualValue
                                formulaValue:(nonnull NSString *)formulaValue
{
    return [[self alloc] initWithRow:row
                              column:column
                         actualValue:actualValue
                        formulaValue:formulaValue];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p row:%@ column:%@ actualValue:%@ formulaValue:%@>", self.class, (void *)self, @(self.row), @(self.column), self.actualValue, self.formulaValue];
}

@end
