// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

package com.example.sankar_5526.helloworld;

import java.util.ArrayList;

public final class Cell {


    /*package*/ final String mFormulaValue;

    /*package*/ final String mActualValue;

    /*package*/ final ArrayList<String> mDependents;

    /*package*/ final ArrayList<String> mPrecedents;

    /*package*/ final ArrayList<String> mExpressionTokens;

    public Cell(
            String formulaValue,
            String actualValue,
            ArrayList<String> dependents,
            ArrayList<String> precedents,
            ArrayList<String> expressionTokens) {
        this.mFormulaValue = formulaValue;
        this.mActualValue = actualValue;
        this.mDependents = dependents;
        this.mPrecedents = precedents;
        this.mExpressionTokens = expressionTokens;
    }

    public String getFormulaValue() {
        return mFormulaValue;
    }

    public String getActualValue() {
        return mActualValue;
    }

    public ArrayList<String> getDependents() {
        return mDependents;
    }

    public ArrayList<String> getPrecedents() {
        return mPrecedents;
    }

    public ArrayList<String> getExpressionTokens() {
        return mExpressionTokens;
    }

    @Override
    public String toString() {
        return "Cell{" +
                "mFormulaValue=" + mFormulaValue +
                "," + "mActualValue=" + mActualValue +
                "," + "mDependents=" + mDependents +
                "," + "mPrecedents=" + mPrecedents +
                "," + "mExpressionTokens=" + mExpressionTokens +
        "}";
    }

}
