// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

package com.example.sankar_5526.helloworld;

public abstract class MyClientInterface {
    public abstract void logString(String str);
}
