// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dependency_evaluator.djinni

package com.example.sankar_5526.helloworld;

public final class UpdatedValues {


    /*package*/ final int mRow;

    /*package*/ final int mColumn;

    /*package*/ final String mActualValue;

    /*package*/ final String mFormulaValue;

    public UpdatedValues(
            int row,
            int column,
            String actualValue,
            String formulaValue) {
        this.mRow = row;
        this.mColumn = column;
        this.mActualValue = actualValue;
        this.mFormulaValue = formulaValue;
    }

    public int getRow() {
        return mRow;
    }

    public int getColumn() {
        return mColumn;
    }

    public String getActualValue() {
        return mActualValue;
    }

    public String getFormulaValue() {
        return mFormulaValue;
    }

    @Override
    public String toString() {
        return "UpdatedValues{" +
                "mRow=" + mRow +
                "," + "mColumn=" + mColumn +
                "," + "mActualValue=" + mActualValue +
                "," + "mFormulaValue=" + mFormulaValue +
        "}";
    }

}
